### PR TITLE
Add a unit test for  NAS Classifier

### PR DESCRIPTION
**Pull request by shendiaomo**

### CODE REVIEW

**Comment by typhoonzero** [comment]
@shendiaomo can you please also add a test case under models repo?

**Comment by shendiaomo** [comment]
> @shendiaomo can you please also add a test case under models repo?

It will be done later because the test framework in models repo only works for Keras models at the moment.

**Comment by shendiaomo** [comment]
> > @shendiaomo can you please also add a test case under models repo?
> 
> It will be done later because the test framework in models repo only works for Keras models at the moment.

The unit test is in sql-machine-learning/models/pull/51

**Review by typhoonzero — APPROVED** [review]
Cool

**Pull request merged**
