### PR TITLE
Resolve issue #326 by adding overview section

### LINKED ISSUE #326: "Quick Overview"
A "Quick Overview" is needed on the [home](https://github.com/sql-machine-learning/sqlflow#how-to-use-sqlflow) to demonstrate how SQLFlow can quickly complete the training and prediction tasks.

Examples of training：
```sql
SELECT *
FROM iris.train
TRAIN DNNClassifier
LABEL class
INTO my_dnn_model;
```

Examples of prediction:
```sql
SELECT *
FROM iris.test
PREDICT iris.predict.class
USING my_dnn_model;
```

### PR DESCRIPTION
**Pull request by hungry1526**
Fix https://github.com/sql-machine-learning/sqlflow/issues/326.

- Add an overview section in github doc home
- Elaborate in installation.md and add link to the demo.md
- TODO: We could however combine demo.md and installation.md in the future, and add more tutorials in SQLFlow in the new demo.md.

### CODE REVIEW

**Comment by hungry1526** [comment]
CI failed, docker run exit with 2, is it a known network issue?

---

Step 6/34 : RUN pip3 install --upgrade pip failed with handshake timeout exception.

**Comment by wangkuiyi** [comment]
It seems that the CI was suffering from a connection problem with the PyPI server. I retriggered the CI.

**Review by wangkuiyi — APPROVED** [review]
Thanks to @hungry1526 for this PR!

**Comment by hungry1526** [comment]
> It seems that the CI was suffering from a connection problem with the PyPI server. I retriggered the CI.

Can I kick off an CI on my own or has to wait for one of the repo admins? Also I see this issue from time to time when doing docker build in China, does it happen to the build machine abroad as well? 

@wangkuiyi

**Comment by tonyyang-svail** [comment]
> It seems that the CI was suffering from a connection problem with the PyPI server. I retriggered the CI.

@wangkuiyi CI still failed after retriggering. https://travis-ci.com/sql-machine-learning/sqlflow/builds/110596545

I have restarted the other two builds: [build1](https://travis-ci.org/sql-machine-learning/sqlflow/jobs/527767546) and [build2](https://travis-ci.com/sql-machine-learning/sqlflow/builds/110521688). Both have passed.

I suspect this failure is related to a specific CI machine, so it is safe to merge with `Travis CI - Branch` hanging.

**Comment by tonyyang-svail** [comment]
> It seems that the CI was suffering from a connection problem with the PyPI server. I retriggered the CI.

@wangkuiyi CI still fails after retriggering. https://travis-ci.com/sql-machine-learning/sqlflow/builds/110596545

I have restarted the other two builds: [build1](https://travis-ci.org/sql-machine-learning/sqlflow/jobs/527767546) and [build2](https://travis-ci.com/sql-machine-learning/sqlflow/builds/110521688). Both have passed.

I suspect this failure is related to a specific CI machine, so it is safe to merge with `Travis CI - Branch` hanging.

**Pull request merged**
