### PR TITLE
[couler-bug-fix-issue-1766] update the env to respect the bool type

### PR DESCRIPTION
**Pull request by merlintang**
This is the bug fix for the [issue](https://github.com/sql-machine-learning/sqlflow/issues/1766)

### CODE REVIEW

**Comment by Yancey0623** [comment]
Hi @merlintang, thanks for resolving this bug, please assign the CLA so that we can merge this PR.

**Comment by merlintang** [comment]
can you give me the link for the CLA?

**Comment by merlintang** [comment]
done for the CLA

**Review by Yancey0623 — APPROVED** [review]
LGTM

**Pull request merged**
