### PR TITLE
line feed for reading

### PR DESCRIPTION
**Pull request by yake0176**
line feed for reading
https://sql-machine-learning.github.io/sqlflow/doc/database_abstraction_layer.html

### CODE REVIEW

**Review by llxxxll — APPROVED** [review]
Approve！

**Review by llxxxll — CHANGES_REQUESTED** [review]
The code is not fully expanded.

**Review by llxxxll — APPROVED** [review]
LGTM！

**Comment by yake0176** [comment]
line feed for read

**Pull request merged**
