### PR TITLE
fix didi folder to aspara2019

### PR DESCRIPTION
**Pull request by Yancey0623**

### CODE REVIEW

**Comment by weiguoz** [comment]
`activepower_clustering/README.md` and `carprice_xgboost/README.md` need to be updated

**Comment by Yancey0623** [comment]
> activepower_clustering/README.md and carprice_xgboost/README.md need to be updated
Thanks @weiguoz , done.

**Review by weiguoz — APPROVED** [review]
LGTM

**Review by typhoonzero — APPROVED** [review]

**Comment by tonyyang-svail** [comment]
There are still some leftovers.
```
$ git grep didi
doc/tutorial/aspara2019/Dockerfile:COPY titanic_dnn/README.md /didi_tutorial/titanic_dnn.md
doc/tutorial/aspara2019/Dockerfile:COPY carprice_xgboost/README.md /didi_tutorial/carprice_xgboost.md
doc/tutorial/aspara2019/Dockerfile:COPY activepower_clustering/README.md /didi_tutorial/activepower_clustering.md
doc/tutorial/aspara2019/Dockerfile:    SRC_FOLDER=/didi_tutorial bash /convert_markdown_into_ipynb.sh
doc/tutorial/aspara2019/README.md:2. Run SQLflow by typing the command `docker run -it -p 8888:8888 sqlflow/sqlflow:didi`.
doc/tutorial/aspara2019/README.md:We thank the data scientists and software engineers from [Didi Chuxing](https://www.didiglobal.com/), especially [@Echo9573](https://github.com/Echo9573) and [@BlackPoint-CX](https://github.com/BlackPoint-CX), for contributing them.
```

Most importantly, we might need to change `docker run -it -p 8888:8888 sqlflow/sqlflow:didi` to `docker run -it -p 8888:8888 sqlflow/sqlflow:aspara2019` at https://github.com/sql-machine-learning/sqlflow/tree/develop/doc/tutorial/aspara2019#quick-start.

**Pull request merged**
