### PR TITLE
[SHAP] support specify plot_type

### PR DESCRIPTION
**Pull request by weiguoz**
```SQL
SELECT *
FROM iris.train
ANALYZE sqlflow_models.my_xgboost_model
WITH
    shap.plot_type="bar"
USING TreeExplainer;
```
The default value of shap.plot_type is specified by SHAP:
https://github.com/slundberg/shap/blob/9c24ffc0cc7f8fbd3874b9594b23cdaa6af4b3d2/shap/plots/summary.py#L39-L54

### CODE REVIEW

**Comment by Echo9573** [comment]
Because different tasks model has the different default values of the plot_type. if it is a classification model, plot_type=bar. If you specify plot_type=dot, an error will be reported; if it is a regression model, plot_type=dot or plot_type=bar can be used. Therefore, sqlflow can specify default values by judging the task type of the model.

**Review by Echo9573 — COMMENTED** [review]
Because different tasks model has the different default values of the plot_type. if it is a classification model, plot_type=bar. If you specify plot_type=dot, an error will be reported; if it is a regression model, plot_type=dot or plot_type=bar can be used. Therefore, sqlflow can specify default values by judging the task type of the model.

**Comment by weiguoz** [comment]
> Because different tasks model has the different default values of the plot_type. if it is a classification model, plot_type=bar. If you specify plot_type=dot, an error will be reported; if it is a regression model, plot_type=dot or plot_type=bar can be used. Therefore, sqlflow can specify default values by judging the task type of the model.

Thanks for your explanation which helps me a lot. I would like to specify the default value by SHAP. 
SHAP judges the task type of the model, and SQLFlow doesn't care about the default value.

**Review by Echo9573 — DISMISSED** [review]

**Comment by Yancey0623** [comment]
Hi @weiguoz , please merge the develop branch to fix the CI timeout.

**Review by Yancey0623 — APPROVED** [review]
LGTM

**Pull request merged**
