### PR TITLE
Move ALPS and EDL to codegen

### PR DESCRIPTION
**Pull request by tonyyang-svail**
Part of #1126.

Also notifying @ly120983.

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
Why are these moved to text files? What's the purpose of moving these around and commenting out if they are not working after the move?

**Comment by tonyyang-svail** [comment]
@terrytangyuan I put them as text files to disable tests.

**Comment by terrytangyuan** [comment]
@tonyyang-svail What's the purpose of moving these around and commenting out if they will not be working after the move?

**Comment by tonyyang-svail** [comment]
@terrytangyuan Please allow me to explain.

I am currently working SQLFlow's parser which requires an incompatible change on ALPS and EDL. Since the code generators of ALPS and EDL will be depending on `pkg/sql/codegen/intermediate_representation.go`, so I am moving them from `pkg/sql` to `pkg/codegen/engine_name`.

**Comment by tonyyang-svail** [comment]
I will come up with a smoother transition plan.

**Comment by terrytangyuan** [comment]
@tonyyang-svail I see. Thanks. Please keep me posted.

**Pull request closed without merging**
