### PR TITLE
Remove unused ALPS Python code

### PR DESCRIPTION
**Pull request by tonyyang-svail**

### CODE REVIEW

**Comment by typhoonzero** [comment]
Can we keep this until we are so sure that it could be removed?

**Comment by tonyyang-svail** [comment]
Has the ALPS related Go code been removed? Shall we keep Go&Python consistent?

**Comment by typhoonzero** [comment]
> Has the ALPS related Go code been removed?

Yes, it's already removed, I think it's better to keep the python code so that we can add the go codegens when we need it.

**Comment by tonyyang-svail** [comment]
Sure.

**Pull request closed without merging**
