### PR TITLE
Remove logrus

### LINKED ISSUE #896: Remove logrus
As a follow-up of https://github.com/sql-machine-learning/sqlflow/issues/781#issuecomment-528211632, let us remove logrus.

### PR DESCRIPTION
**Pull request by wangkuiyi**
Fix https://github.com/sql-machine-learning/sqlflow/issues/896

### CODE REVIEW

**Comment by typhoonzero** [comment]
Go's log does not have `Errorf`, `Debugf` etc. Should change to `log.Printf`

**Comment by wangkuiyi** [comment]
The CI failed with errors

```
The command "docker pull sqlflow/sqlflow:latest && docker build --cache-from sqlflow/sqlflow:latest -t sqlflow:latest -f Dockerfile ." exited with 0.
$ docker run --rm -v $GOPATH/src:/go/src -w /go/src/github.com/sql-machine-learning/sqlflow sqlflow:latest pre-commit run -a
[INFO] Initializing environment for git://github.com/dnephin/pre-commit-golang.
[INFO] Initializing environment for https://github.com/wangkuiyi/google-style-precommit-hook.
go fmt...................................................................Passed
go lint..................................................................Failed
hookid: go-lint
server/sqlflowserver.go:20:1: package comment is detached; there should be no blank lines between it and the package statement
Found 1 lint suggestions; failing.
validate toml........................................(no files to check)Skipped
Check files aren't using go's testing package........(no files to check)Skipped
Google Java Code Style for Java..........................................Passed
copyright_checker........................................................Failed
hookid: copyright_checker
Files were modified by this hook. Additional output:
Auto Insert Copyright Header sql/parser.go
Traceback (most recent call last):
  File "./scripts/copyright.py", line 137, in <module>
    exit(main())
  File "./scripts/copyright.py", line 131, in main
    output_file.write(new_contents)
UnicodeEncodeError: 'ascii' codec can't encode character '\u03b5' in position 16649: ordinal not in range(128)
```

I have no idea why the copyright checker would fail. Will need to figure it out tomorrow.

**Comment by tonyyang-svail** [comment]
@wangkuiyi the error is due to the epsilon character

https://github.com/sql-machine-learning/sqlflow/blob/5cc99bc89fd7de1f65ea1c1709db4c569b111661/pkg/sql/parser.go#L782

Looks like this character is generated by `goyacc`. I will fix it in our python script.

**Comment by tonyyang-svail** [comment]
Hi @wangkuiyi, I am closing this PR since it contains the logic of adding `goyacc`.

I filed a PR to add `goyacc` #946. And I will file another PR to remove the logrus.

**Pull request closed without merging**
