### PR TITLE
Add go module in SQLFlow

### PR DESCRIPTION
**Pull request by WingGao**

### CODE REVIEW

**Comment by weiguoz** [comment]
Would you please add some comments about the purpose of this PR :)

**Comment by WingGao** [comment]
Using go module will make the sqlflow build to be more reliable and reproducible.
And for those who use go module as the dependency management will need this `go.mod` file while use this project from `fork`.

**Comment by wangkuiyi** [comment]
HI @WingGao , thank you very much for this PR! I can see how carefully you listed the dependencies and verified their versions. And I believe we will need the Go module someday in the future.

Unfortunately, SQLFlow is currently under very active development, the dependencies are subject to frequent and significant changes -- no to mention their versions.

How about we add Go modules back when we reach version 1.0 in the next few months when the software is production-ready?

Thank you again for this contribution. We look forward to more from you!

**Comment by tonyyang-svail** [comment]
Kindly close this PR for now.

**Pull request closed without merging**
