### PR TITLE
[wip] XgBoost training

### PR DESCRIPTION
**Pull request by tonyyang-svail**

### CODE REVIEW

**Review by tonyyang-svail — COMMENTED** [review]
This PR is too large to be reviewed properly. I will split it into separate PRs.

**Comment by Yancey0623** [comment]
Hi @tonyyang-svail , do you want to create an issue for the whole IR tasks?

**Comment by tonyyang-svail** [comment]
@Yancey1989 You can find the TODO list for making XgBoost codegen at https://github.com/sql-machine-learning/sqlflow/issues/805

**Comment by Yancey0623** [comment]
Hi @tonyyang-svail , seems this PR can be closed because I saw another PR to implement the xgboost train codegen: #829

**Comment by tonyyang-svail** [comment]
@Yancey1989 You are right.

**Pull request closed without merging**
