### PR TITLE
Put Go code in the go directory

### PR DESCRIPTION
**Pull request by shendiaomo**
Move Go code to `go` directory as described in https://github.com/sql-machine-learning/sqlflow/issues/2494#issuecomment-650658819

### CODE REVIEW

**Comment by wangkuiyi** [comment]
Given that we are going to have the `go` directory, do we still need the `pkg` directory? How about renaming `pkg` into `go` and move `cmd` into `go/cmd`?  This alternative is pretty common in Go world as well, for example https://github.com/qiniu/goplus.

**Comment by shendiaomo** [comment]
> Given that we are going to have the `go` directory, do we still need the `pkg` directory? How about renaming `pkg` into `go` and move `cmd` into `go/cmd`? This alternative is pretty common in Go world as well, for example https://github.com/qiniu/goplus.

Done.

**Review by Yancey0623 — DISMISSED** [review]
LGTM

**Review by typhoonzero — DISMISSED** [review]

**Comment by typhoonzero** [comment]
Need to resolve the conflict

**Review by lhw362950217 — DISMISSED** [review]
LGTM

**Comment by shendiaomo** [comment]
> Need to resolve the conflict

Done.

**Review by typhoonzero — APPROVED** [review]

**Pull request merged**
