### PR TITLE
Support explaining DNNs using SHAP

### PR DESCRIPTION
**Pull request by shendiaomo**
This is based on the discussion in https://github.com/slundberg/shap/issues/280
The screenshot looks like:
image

### CODE REVIEW

**Review by wangkuiyi — DISMISSED** [review]

**Review by wangkuiyi — DISMISSED** [review]

**Comment by tonyyang-svail** [comment]
Hi @shendiaomo, thanks for submitting this PR. Could you please add SQLs in the demo as our test cases?

**Comment by typhoonzero** [comment]
Maybe also test case like `explain_example.py` and call it in the test `train_predict_test.py`

**Review by wangkuiyi — DISMISSED** [review]

**Comment by shendiaomo** [comment]
> Hi @shendiaomo, thanks for submitting this PR. Could you please add SQLs in the demo as our test cases?

Done.

**Comment by shendiaomo** [comment]
> Maybe also test case like `explain_example.py` and call it in the test `train_predict_test.py`

Later in another PR?

**Review by wangkuiyi — APPROVED** [review]

**Pull request merged**
