### PR TITLE
Remove miniconda

### LINKED ISSUE #517: Do we need miniconda in Dockerfile
Is the only purpose to introduce miniconda is to install Python 3?

If so, it seems that we can easily install Python 3.6 on Ubuntu 16.04 by following http://ubuntuhandbook.org/index.php/2017/07/install-python-3-6-1-in-ubuntu-16-04-lts/, and could save many lines of code as follows:

https://github.com/sql-machine-learning/sqlflow/blob/1a46d471e36484e9421e533755b0c1bc9aaef381/scripts/image_build.sh#L19-L40

### PR DESCRIPTION
**Pull request by wangkuiyi**
c.f. https://github.com/sql-machine-learning/sqlflow/pull/1598#issue-358507866

Fix https://github.com/sql-machine-learning/sqlflow/issues/517

### CODE REVIEW

**Comment by wangkuiyi** [comment]
After using Python 3.5 on Ubuntu 14.04,  the command `pip install shap==0.30.1` prints the following error message.

```
ollecting shap==0.30.1
  Downloading https://files.pythonhosted.org/packages/c9/b3/76dc7e0a039543ff8646e453b3a28bfd55a1954f91a6bc7b6ed8be80bf16/shap-0.30.1.tar.gz (244kB)
ERROR: Files/directories not found in /tmp/pip-install-91ushre8/shap/pip-egg-info
```

I switched to use a new version, shap==0.34.0, released in late Dec 2019. And I got the same error.

Then, I switched to shap==0.19.1 released on Jun 28, 2018. Same error.

I guess that shap is picky and wants Python 3.6

**Comment by wangkuiyi** [comment]
As SHAP wants Python 3.6, but Ubuntu 16.04 comes with only Python 3.5, we might want to try install Python 3.6 from a PPA. Unfortunately, we can no longer do that as the PPA author decided to remove his work from the public domain, as explained in https://launchpad.net/~jonathonf/+archive/ubuntu/python-3.6.  

The choices left are

1. Switch to Ubuntu 18.04, the latest LTS having Python 3.6. 
1. Install Python from source code.
1. Keep using Miniconda to install Python 3.6.

**Comment by wangkuiyi** [comment]
OK. We switched to Python 3.6 in https://github.com/sql-machine-learning/sqlflow/pull/1600.

**Comment by wangkuiyi** [comment]
CI failed with multiple problems.

1. Building pip mysqlclient needs to install libdev-ssl.
1. `ERROR: plotille 3.7 has requirement six<2.0,>=1.12, but you'll have six 1.11.0 which is incompatible.`

**Comment by wangkuiyi** [comment]
CI failed due to error

```
Processing dependencies for elasticdl===develop
error: setuptools 39.0.1 is installed but setuptools>=40.3.0 is required by {'google-auth'}
The command '/bin/sh -c /install-elasticdl.bash' returned a non-zero code: 1
```

Trying to fix it following https://github.com/red-hat-storage/ocs-ci/pull/971/files

**Comment by wangkuiyi** [comment]
The CI with mysql failed but all other CI jobs succeeded.  The error message is as following.

```
======================================================================
ERROR: test_estimator (sqlflow_submitter.tensorflow.train_predict_test.TestEstimatorModels)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/go/src/sqlflow.org/sqlflow/python/sqlflow_submitter/tensorflow/train_predict_test.py", line 26, in test_estimator
    env={"PYTHONPATH": "python"})
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'python'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/go/src/sqlflow.org/sqlflow/python/sqlflow_submitter/tensorflow/train_predict_test.py", line 29, in test_estimator
    self.fail("%s" % ret.stderr)
UnboundLocalError: local variable 'ret' referenced before assignment
======================================================================
ERROR: test_keras (sqlflow_submitter.tensorflow.train_predict_test.TestEstimatorModels)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/go/src/sqlflow.org/sqlflow/python/sqlflow_submitter/tensorflow/train_predict_test.py", line 35, in test_keras
    env={"PYTHONPATH": "python"})
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'python'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/go/src/sqlflow.org/sqlflow/python/sqlflow_submitter/tensorflow/train_predict_test.py", line 38, in test_keras
    self.fail("%s" % ret.stderr)
UnboundLocalError: local variable 'ret' referenced before assignment
----------------------------------------------------------------------
Ran 11 tests in 1.327s
FAILED (errors=2)
Evaluation result: {'train': {'rmse': [17.116695, 12.300258, 8.955046, 6.570806, 4.889098, 3.696858, 2.881636, 2.307854, 1.929176, 1.621072, 1.429485, 1.300483, 1.194412, 1.096546, 1.035647, 0.981582, 0.932085, 0.867206, 0.840945, 0.799894, 0.766308, 0.712008, 0.677878, 0.629921, 0.609242, 0.585225, 0.536009, 0.493594, 0.47246, 0.444385]}}
The command "docker run --rm -v $GOPATH:/root/go -w /root/go/src/sqlflow.org/sqlflow sqlflow:latest bash scripts/test/units.sh" exited with 1.
```

**Comment by wangkuiyi** [comment]
I started a sqlflow container locally, and ran `python python/sqlflow_submitter/tensorflow/estimator_example.py` in it, and got the following error message

```
root@48bb8f52d584:/sqlflow# python python/sqlflow_submitter/tensorflow/estimator_example.py
Traceback (most recent call last):
  File "python/sqlflow_submitter/tensorflow/estimator_example.py", line 16, in <module>
    import sqlflow_submitter
ModuleNotFoundError: No module named 'sqlflow_submitter'
```

Checking the `PYTHONPATH` environment variable, I got

```
root@48bb8f52d584:/sqlflow# echo $PYTHONPATH
/root/go/src/sqlflow.org/sqlflow/python
```

However, in `/root/go/` there is only `pkg` but no `src`.

**Review by terrytangyuan — APPROVED** [review]

**Pull request merged**
