### PR TITLE
Fix swallowed error

### LINKED ISSUE #2023: CI fails on TestRunStmt in repl_test.go
**Description**
https://travis-ci.com/github/sql-machine-learning/sqlflow/jobs/299289488
```
=== RUN   TestRunStmt
FAIL	sqlflow.org/sqlflow/cmd/repl	0.114s
=== RUN   TestWorkflow
```
And there aren't any meaningful message.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by shendiaomo**
Fix #2023 .

### CODE REVIEW

**Comment by Yancey0623** [comment]
Hi @shendiaomo , please take a look at #2024 before merge this fix? Seems the root reason is written `nil` into the pipe and cause the step panic.

**Comment by shendiaomo** [comment]
> Hi @shendiaomo , please take a look at #2024 before merge this fix? Seems the root reason is written `nil` into the pipe and cause the step panic.

I think the core reason is the `err` is overwritten by the first call to `Write` (which is redundant), there'll be no nil written to the pipe after removing the statement.

**Review by Yancey0623 — APPROVED** [review]
LGTM, allow `nil` in pipe can be more robustness, if we don't like to write `nil` to pipe, it's better to raise Error if the content is nil.

**Comment by shendiaomo** [comment]
NOTE: It was #1982 that caused this problem. But it's weird that the CI system didn't utter an error at that moment.  The UT kept succeeding until #2012 was merged.

More investigations still needed.

**Pull request merged**
