### PR TITLE
Tiny refactor of Argo package

### PR DESCRIPTION
**Pull request by tonyyang-svail**
1. Follow https://github.com/sql-machine-learning/sqlflow/pull/1405/files/56602cabdd26806912953a9e2254eb6207489fee#diff-7d90b97355746eff270759119aa131ce
1. Reuse `Submit` for testing

### CODE REVIEW

**Review by typhoonzero — DISMISSED** [review]

**Review by Yancey0623 — APPROVED** [review]
LGTM

**Review by wangkuiyi — CHANGES_REQUESTED** [review]
This change itself looks reasonable to me.  I am blocking it because I believe the overall progress depends on a design doc, as explained https://github.com/sql-machine-learning/sqlflow/issues/1423.

**Comment by typhoonzero** [comment]
@wangkuiyi does this https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/design/high_available_sqlflow_server.md doc answers your question, yet we need to update the design to use the same protobuf definitions.

And, the job status maybe don't need to return to the client as response, see: https://github.com/sql-machine-learning/sqlflow/issues/1410

**Review by wangkuiyi — APPROVED** [review]

**Comment by tonyyang-svail** [comment]
Close due to lack of activity.

**Pull request closed without merging**
