### PR TITLE
Fix broken links in Markdown files

### PR DESCRIPTION
**Pull request by tonyyang-svail**
Changes:
1. Fix broken markdown links
1. Add markdown-link-check script

### CODE REVIEW

**Review by Yancey0623 — COMMENTED** [review]
Excellent PR! Can we add the markdown-link check in the PR CI job?

**Comment by tonyyang-svail** [comment]
@Yancey1989 Adding the link check will definitely make our CI more rigorous.

However, I feel reluctant to add the links-check in our PR CI. Because links failing is beyond of our control, and the failure is often irrelevant to the PR being submitted.

For example, I found another link error just now even though I've fixed all the links yesterday.
```
FILE: ./doc/design/design_customized_model.md
[✓] https://keras.io/
[✖] https://www.tensorflow.org/guide/estimators
[✓] https://www.youtube.com/watch?v=k5c-vg4rjBw
[✓] https://stackoverflow.com/questions/51806852/cant-save-custom-subclassed-model
[✓] https://stackoverflow.com/questions/52826134/keras-model-subclassing-examples
[✓] https://github.com/tensorflow/tensorflow/issues/27416
[✓] https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/models.py
[✓] https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/network.py
[✓] https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/training.py
```

If we put the check in the CI, all the ongoing PRs will be blocked.

**Comment by typhoonzero** [comment]
The link check can be put under pre commit check, recommend: https://github.com/dkhamsing/awesome_bot

**Review by typhoonzero — APPROVED** [review]

**Review by Yancey0623 — APPROVED** [review]
@tonyyang-svail , I see and LGTM.

**Pull request merged**
